services:
  wg-busy:
    build: .
    image: wg-busy:v0.0.3
    container_name: wg-busy
    security_opt:
      - systempaths=unconfined
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    ports:
      - "8080:8080" # Web UI
      - "51820:51820/udp" # WireGuard
    volumes:
      - ./data:/app/data # config.yaml persistence
      - /lib/modules:/lib/modules:ro # kernel modules for wireguard
    environment:
      - WG_BUSY_LISTEN=:8080
      - WG_BUSY_CONFIG=/app/data/config.yaml
      - WG_BUSY_WG_CONFIG=/etc/wireguard/wg0.conf
    restart: unless-stopped
